apiVersion: apps/v1
kind: Deployment
metadata:
  name: roy-nginx
spec:
  selector:
    matchLabels:
      app: roy-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: roy-nginx
    spec:
      containers:
        - name: roy-nginx
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
